[package]
name = "libprosic"
version = "0.1.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = "0.7.0"
log = "0.3.*"
rust-htslib = { git="https://github.com/rust-bio/rust-htslib.git" }
GSL = "0.4.*"
