[package]
name = "libprosic"
version = "0.1.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = { git = "https://github.com/rust-bio/rust-bio" } # "0.9.0"
log = "0.3.*"
rust-htslib = "0.8.*"
GSL = "0.4.*"
itertools = "0.4.*"
approx = "0.1.*"
rusty-machine="0.4.*"
ordered-float = "0.2.*"
ndarray = "0.6"
flame = { version = "^0.1.2", optional = true }
flamer = { version = "^0.1.2", optional = true }
rustc-serialize = "0.3.*"

[features]
default = []
flame_it = ["flame", "flamer"]
