[package]
name = "libprosic"
version = "0.1.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = "0.10.*"
log = "0.3.*"
rust-htslib = "0.9.*"
GSL = "0.4.*"
itertools = "0.4.*"
approx = "0.1.*"
rusty-machine="0.4.*"
ordered-float = "0.2.*"
ndarray = "0.6"
flame = { version = "^0.1.2", optional = true }
flamer = { version = "^0.1.2", optional = true }
rustc-serialize = "0.3.*"
quick-error = "1.1.*"
csv = "0.14.*"

[features]
default = []
flame_it = ["flame", "flamer"]
